### ISSUE TITLE
New update in PyTorch break forces

### ISSUE THREAD

**Issue by zasdfgbnm** [aiqm/torchani#276]
@farhadrgh @IgnacioJPickering 
Just tested `python tests/test_forces.py` with a newest freshly compiled PyTorch, get the following error:
```text
FFF.F
======================================================================
FAIL: testBenzeneMD (__main__.TestForce)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_forces.py", line 89, in testBenzeneMD
    self.assertLess(max_diff, tolerance)
AssertionError: 30.85953140258789 not less than 1e-05

======================================================================
FAIL: testIsomers (__main__.TestForce)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_forces.py", line 42, in testIsomers
    self.assertLess(max_diff, self.tolerance)
AssertionError: 0.5897072553634644 not less than 1e-05

======================================================================
FAIL: testNIST (__main__.TestForce)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_forces.py", line 125, in testNIST
    self.assertLess(max_diff, self.tolerance)
AssertionError: 4.202903747558594 not less than 1e-05

======================================================================
FAIL: testTripeptideMD (__main__.TestForce)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_forces.py", line 108, in testTripeptideMD
    self.assertLess(max_diff, tolerance)
AssertionError: 22.5817928314209 not less than 2e-06

----------------------------------------------------------------------
Ran 5 tests in 64.475s

FAILED (failures=4)
```

**Comment by zasdfgbnm** [comment]
`torch_nightly==1.2.0.dev20190801` works well
`torch_nightly==1.2.0.dev20190802` is broken

**Comment by zasdfgbnm** [comment]
git version:
`torch_nightly==1.2.0.dev20190801`: `ec13f18390c03e3dfa5c6cb7e4e5b7e0798c1532`

**Comment by zasdfgbnm** [comment]
bisect:
`3b5daef6dec7b541a74e33a9a0b0646941b0440d`

**Comment by zasdfgbnm** [comment]
The problem comes from a breaking change introduced in: https://github.com/pytorch/pytorch/pull/21113
I am not sure whether this new bc-breaking PR introduces a new bug in PyTorch, or it requires user codes like us to change.

Looking further deep into that now...

**Comment by zasdfgbnm** [comment]
Tests in `test_aevs` and `test_energies` are also failing.
