### ISSUE TITLE
Error in nnp_training,py: pickle the dataset after loading

### ISSUE THREAD

**Issue by grassdeerdeer** [aiqm/torchani#656]
When I pickle the dataset after loading, I meet this problem:

In torchani/torchani/data/_pyanitools.py 52 line:
```
dataset = np.array(item[k][()])
```
We meet this problem: ValueError('Insufficient precision in available types to represent (31, 23, 8, 0, 23)').

Could you please give me some suggestions about this problem? Thank you very much!

**Comment by grassdeerdeer** [comment]
Or could you please give me 'dataset.pkl'? Thank you very much!

**Comment by IgnacioJPickering** [comment]
Hello @grassdeerdeer, We will soon be updating the library to a new version and training with `training_nnp.py` is not recommended anymore, I suggest you rely on your own training script for now.

**Comment by varun-go** [comment]
Hello, 

I am also having an issue with running `nnp_training.py`. Specifically, the issue is in processing the dataset:

https://github.com/aiqm/torchani/blob/17204c6dccf6210753bc8c0ca4c92278b60719c9/examples/nnp_training.py#L113-L117

The error I receive is: 

```
Processing dataset in /Users/varun/research/torchani/examples/../dataset/ani1-up_to_gdb4/ani_gdb_s01.h5
Traceback (most recent call last):
  File "/Users/varun/software/miniconda3/envs/hydrogel/lib/python3.10/pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "/Users/varun/software/miniconda3/envs/hydrogel/lib/python3.10/pdb.py", line 1583, in _runscript
    self.run(statement)
  File "/Users/varun/software/miniconda3/envs/hydrogel/lib/python3.10/bdb.py", line 598, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/varun/research/torchani/examples/nnp_training.py", line 114, in <module>
    .subtract_self_energies(energy_shifter, species_order)\
  File "/Users/varun/software/miniconda3/envs/hydrogel/lib/python3.10/site-packages/torchani/data/__init__.py", line 298, in f
    transformation(self.wrapped_iterable, *args, **kwargs),
  File "/Users/varun/software/miniconda3/envs/hydrogel/lib/python3.10/site-packages/torchani/data/__init__.py", line 191, in subtract_self_energies
    sae, _, _, _ = numpy.linalg.lstsq(X, Y, rcond=None)
  File "/Users/varun/software/miniconda3/envs/hydrogel/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 2293, in lstsq
    _assert_2d(a, b)
  File "/Users/varun/software/miniconda3/envs/hydrogel/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 200, in _assert_2d
    raise LinAlgError('%d-dimensional array given. Array must be '
numpy.linalg.LinAlgError: 1-dimensional array given. Array must be two-dimensional
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
```

I understand the library will be updated to a new version, but is this error expected? Is there a previous version of the code that we could use that would not produce this error? Thank you!

**Comment by IgnacioJPickering** [comment]
@varun-go Hello! Please use the latest version of the library (`pip install --upgrade torchani`, or better, follow the installation instructions from scratch). This will hopefully solve your issues. I'll leave this issue open for now since it is not that old. Ping me if you have any questions
